# Generated by Django 5.1.1 on 2024-11-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neides', '0002_auto_XXXX'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('salgado', 'Salgado'), ('doce', 'Doce'), ('bebida', 'Bebida')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
